apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/cpulcini2003/webapi
      title: GitHub Repo
      icon: github
    - url: https://github.com/cpulcini2003/webapi/blob/main/petstoreopenapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi: 3.0.2
  servers:
    - url: /v3
  info:
  
